### PR TITLE
Add new actions (add, upsert, get, getAll)

### PR DESCRIPTION
**Pull request by matmunn**
Builds off #2 and adds some new actions for creating/updating/fetching records

### CODE REVIEW

**Comment by jmagnusson** [comment]
Hi @matmunn,

Thanks for your contribution - looks very promising!

My schedule is a bit crazy now so I will be unable to look at/merge this for the time being, hope you have another way of doing your builds without going through PyPI.

**Comment by WesleyBatista** [comment]
@matmunn :clap: :clap: :clap: for the PR!

I did not verified pretty much closer, but seems really cool. would be amazing to have pagination support too.

Not sure if it happens with `self.Core.GetAllRecord`, but trying to retrieve **Customers** through a search, the result was being limited to 1000. _the relevant piece of code is this_:
```python
        search_string = SearchStringField(**{
            'operator': 'contains',
            'searchValue': ''
        })
        customer_search_basic = CustomerSearchBasic(companyName=search_string)
        record = CustomerSearch(basic=customer_search_basic)
        response = client.request('search', record)
```

I saw some PHP code using the [`searchMoreWithId`](http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/other/searchmorewithidrequest.html?mode=package) method, although not able to use it on python with this package due to a **ValidationError** exception that is raised with the `pageIndex` parameter...

I noticed that because my Netsuite Version was diverging from the [PHP code](https://github.com/ryanwinchester/netsuite-php#token-based-authentication) that I've found, so I tried _(again)_ to downgrade the Netsuite version with this package to `2017.1`, which led me to here :sweat:

**Comment by jmagnusson** [comment]
@matmunn Getting ready to test your PR, can you perhaps rebase towards master? (Remove changes included from #2 as it was fixed in #5)

**Comment by jmagnusson** [comment]
Replaced with #6

**Pull request closed without merging**
